/*
 * Copyright 2024 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v16.0
processor: MCXA344
package_id: MCXA344VLQ
mcu_data: ksdk2_0
processor_version: 0.0.0
pin_labels:
- {pin_num: '144', pin_signal: P1_7/WUU0_IN9/TRIG_OUT2/LPUART2_CTS_B/CT_INP7/CT4_MAT1/EZH_PIO3/ADC0_A23, label: SW2, identifier: SW2}
- {pin_num: '115', pin_signal: P0_6/ISPMODE_N/LPI2C0_HREQ/LPSPI0_PCS1/CT_INP2/EZH_PIO2/CMP1_OUT/CLKOUT/ADC0_A15, label: SW3, identifier: SW3}
- {pin_num: '86', pin_signal: P3_18/LPUART4_RXD/CT2_MAT0/PWM0_X0/PWM1_X0/EZH_PIO18, label: LED_RED, identifier: LED_RED}
- {pin_num: '85', pin_signal: P3_19/LPUART4_TXD/CT2_MAT1/PWM0_X1/PWM1_X1/EZH_PIO19, label: LED_GREEN, identifier: LED_GREEN}
- {pin_num: '82', pin_signal: P3_21/TRIG_OUT1/LPI2C3_SCL/LPUART1_TXD/CT2_MAT3/PWM0_X3/PWM1_B3/EZH_PIO21/ADC3_A19, label: LED_BLUE, identifier: LED_BLUE}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitDEBUG_UARTPins();
   // BOARD_InitI2CPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitDEBUG_UARTPins:
- options: {callFromInitBoot: 'true', coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '36', peripheral: LPUART2, signal: RX, pin_signal: P2_3/WUU0_IN19/TRIG_IN7/LPUART0_CTS_B/LPUART2_RXD/CT_INP13/CT2_MAT3/EZH_PIO27/ADC0_A3/CMP1_IN0/ADC1_A4,
    slew_rate: fast, open_drain: disable, drive_strength: low, pull_select: up, pull_enable: enable, input_buffer: enable, invert_input: normal}
  - {pin_num: '35', peripheral: LPUART2, signal: TX, pin_signal: P2_2/TRIG_IN6/LPUART0_RTS_B/LPUART2_TXD/CT_INP12/CT2_MAT2/EZH_PIO26/ADC0_A4/CMP0_IN0/DAC0_OUT, slew_rate: fast,
    open_drain: disable, drive_strength: low, pull_select: up, pull_enable: enable, input_buffer: enable, invert_input: normal}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitDEBUG_UARTPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitDEBUG_UARTPins(void)
{
    CLOCK_EnableClock(kCLOCK_GatePORT0);
    CLOCK_EnableClock(kCLOCK_GatePORT1);
    CLOCK_EnableClock(kCLOCK_GatePORT2);
    CLOCK_EnableClock(kCLOCK_GatePORT3);
    
    RESET_ReleasePeripheralReset(kLPUART0_RST_SHIFT_RSTn);
    RESET_ReleasePeripheralReset(kLPUART1_RST_SHIFT_RSTn);
    RESET_ReleasePeripheralReset(kLPUART2_RST_SHIFT_RSTn);
    RESET_ReleasePeripheralReset(kLPUART3_RST_SHIFT_RSTn);
    
    RESET_ReleasePeripheralReset(kPORT0_RST_SHIFT_RSTn);
    RESET_ReleasePeripheralReset(kPORT1_RST_SHIFT_RSTn);
    RESET_ReleasePeripheralReset(kPORT2_RST_SHIFT_RSTn);
    RESET_ReleasePeripheralReset(kPORT3_RST_SHIFT_RSTn);
    
    RESET_ReleasePeripheralReset(kADC0_RST_SHIFT_RSTn);
    RESET_ReleasePeripheralReset(kADC1_RST_SHIFT_RSTn);
    
    RESET_ReleasePeripheralReset(kOPAMP0_RST_SHIFT_RSTn);
    RESET_ReleasePeripheralReset(kOPAMP1_RST_SHIFT_RSTn);
    RESET_ReleasePeripheralReset(kOPAMP2_RST_SHIFT_RSTn);
    
    RESET_ReleasePeripheralReset(kINPUTMUX0_RST_SHIFT_RSTn);
        
    const port_pin_config_t port1_5_pin35_config = {/* Internal pull-up resistor is enabled */
                                                    .pullSelect = kPORT_PullUp,
                                                    /* Low internal pull resistor value is selected. */
                                                    .pullValueSelect = kPORT_LowPullResistor,
                                                    /* Fast slew rate is configured */
                                                    .slewRate = kPORT_FastSlewRate,
                                                    /* Passive input filter is disabled */
                                                    .passiveFilterEnable = kPORT_PassiveFilterDisable,
                                                    /* Open drain output is disabled */
                                                    .openDrainEnable = kPORT_OpenDrainDisable,
                                                    /* Low drive strength is configured */
                                                    .driveStrength = kPORT_LowDriveStrength,
                                                    /* Normal drive strength is configured */
                                                    .driveStrength1 = kPORT_NormalDriveStrength,
                                                    /* Pin is configured as LPUART2_TXD */
                                                    .mux = kPORT_MuxAlt3,
                                                    /* Digital input enabled */
                                                    .inputBuffer = kPORT_InputBufferEnable,
                                                    /* Digital input is not inverted */
                                                    .invertInput = kPORT_InputNormal,
                                                    /* Pin Control Register fields [15:0] are not locked */
                                                    .lockRegister = kPORT_UnlockRegister};
    /* PORT2_2 (pin 35) is configured as LPUART2_TXD */
    PORT_SetPinConfig(PORT1, 5, &port1_5_pin35_config);

    const port_pin_config_t port1_4_pin36_config = {/* Internal pull-up resistor is enabled */
                                                    .pullSelect = kPORT_PullUp,
                                                    /* Low internal pull resistor value is selected. */
                                                    .pullValueSelect = kPORT_LowPullResistor,
                                                    /* Fast slew rate is configured */
                                                    .slewRate = kPORT_FastSlewRate,
                                                    /* Passive input filter is disabled */
                                                    .passiveFilterEnable = kPORT_PassiveFilterDisable,
                                                    /* Open drain output is disabled */
                                                    .openDrainEnable = kPORT_OpenDrainDisable,
                                                    /* Low drive strength is configured */
                                                    .driveStrength = kPORT_LowDriveStrength,
                                                    /* Normal drive strength is configured */
                                                    .driveStrength1 = kPORT_NormalDriveStrength,
                                                    /* Pin is configured as LPUART2_RXD */
                                                    .mux = kPORT_MuxAlt3,
                                                    /* Digital input enabled */
                                                    .inputBuffer = kPORT_InputBufferEnable,
                                                    /* Digital input is not inverted */
                                                    .invertInput = kPORT_InputNormal,
                                                    /* Pin Control Register fields [15:0] are not locked */
                                                    .lockRegister = kPORT_UnlockRegister};
    /* PORT2_3 (pin 36) is configured as LPUART2_RXD */
    PORT_SetPinConfig(PORT1, 4, &port1_4_pin36_config);
                                                    
                                                    
                                                    
    const port_pin_config_t port2_12_13_15_16_17_19_config = {/* Internal pull-up/down resistor is disabled */
                                                    .pullSelect = kPORT_PullDisable,
                                                    /* Low internal pull resistor value is selected. */
                                                    .pullValueSelect = kPORT_LowPullResistor,
                                                    /* Fast slew rate is configured */
                                                    .slewRate = kPORT_FastSlewRate,
                                                    /* Passive input filter is disabled */
                                                    .passiveFilterEnable = kPORT_PassiveFilterDisable,
                                                    /* Open drain output is disabled */
                                                    .openDrainEnable = kPORT_OpenDrainDisable,
                                                    /* Low drive strength is configured */
                                                    .driveStrength = kPORT_LowDriveStrength,
                                                    /* Normal drive strength is configured */
                                                    .driveStrength1 = kPORT_NormalDriveStrength,

                                                    .mux = kPORT_MuxAlt0,
                                                    /* Digital input disabled; it is required for analog functions */
                                                    .inputBuffer = kPORT_InputBufferDisable,
                                                    /* Digital input is not inverted */
                                                    .invertInput = kPORT_InputNormal,
                                                    /* Pin Control Register fields [15:0] are not locked */
                                                    .lockRegister = kPORT_UnlockRegister};

    PORT_SetPinConfig(PORT2, 12, &port2_12_13_15_16_17_19_config);
    PORT_SetPinConfig(PORT2, 13, &port2_12_13_15_16_17_19_config);
    PORT_SetPinConfig(PORT2, 15, &port2_12_13_15_16_17_19_config);
    PORT_SetPinConfig(PORT2, 16, &port2_12_13_15_16_17_19_config);
    PORT_SetPinConfig(PORT2, 17, &port2_12_13_15_16_17_19_config);
    PORT_SetPinConfig(PORT2, 19, &port2_12_13_15_16_17_19_config);
                                                    
                                                    
    PORT_SetPinConfig(PORT3, 27, &port2_12_13_15_16_17_19_config);
    PORT_SetPinConfig(PORT3, 28, &port2_12_13_15_16_17_19_config);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitLEDsPins:
- options: {callFromInitBoot: 'false', coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '86', peripheral: GPIO3, signal: 'GPIO, 18', pin_signal: P3_18/LPUART4_RXD/CT2_MAT0/PWM0_X0/PWM1_X0/EZH_PIO18, direction: OUTPUT, gpio_init_state: 'true',
    slew_rate: fast, open_drain: disable, drive_strength: low, pull_select: down, pull_enable: disable, pull_value: low, input_buffer: enable, invert_input: normal}
  - {pin_num: '85', peripheral: GPIO3, signal: 'GPIO, 19', pin_signal: P3_19/LPUART4_TXD/CT2_MAT1/PWM0_X1/PWM1_X1/EZH_PIO19, direction: OUTPUT, gpio_init_state: 'true',
    slew_rate: fast, open_drain: disable, drive_strength: low, pull_select: down, pull_enable: disable, pull_value: low, input_buffer: enable, invert_input: normal}
  - {pin_num: '82', peripheral: GPIO3, signal: 'GPIO, 21', pin_signal: P3_21/TRIG_OUT1/LPI2C3_SCL/LPUART1_TXD/CT2_MAT3/PWM0_X3/PWM1_B3/EZH_PIO21/ADC3_A19, direction: OUTPUT,
    gpio_init_state: 'true', slew_rate: fast, open_drain: disable, drive_strength: low, pull_select: down, pull_enable: disable, input_buffer: enable, invert_input: normal}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitLEDsPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitLEDsPins(void)
{
    /* GPIO3: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GateGPIO3);
    /* PORT3: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT3);
    /* GPIO3 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kGPIO3_RST_SHIFT_RSTn);
    /* PORT3 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT3_RST_SHIFT_RSTn);

    gpio_pin_config_t LED_RED_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PIO3_18 (pin 86)  */
    GPIO_PinInit(BOARD_INITLEDSPINS_LED_RED_GPIO, BOARD_INITLEDSPINS_LED_RED_PIN, &LED_RED_config);

    gpio_pin_config_t LED_GREEN_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PIO3_19 (pin 85)  */
    GPIO_PinInit(BOARD_INITLEDSPINS_LED_GREEN_GPIO, BOARD_INITLEDSPINS_LED_GREEN_PIN, &LED_GREEN_config);

    gpio_pin_config_t LED_BLUE_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PIO3_21 (pin 82)  */
    GPIO_PinInit(BOARD_INITLEDSPINS_LED_BLUE_GPIO, BOARD_INITLEDSPINS_LED_BLUE_PIN, &LED_BLUE_config);

    const port_pin_config_t LED_RED = {/* Internal pull-up/down resistor is disabled */
                                       .pullSelect = kPORT_PullDisable,
                                       /* Low internal pull resistor value is selected. */
                                       .pullValueSelect = kPORT_LowPullResistor,
                                       /* Fast slew rate is configured */
                                       .slewRate = kPORT_FastSlewRate,
                                       /* Passive input filter is disabled */
                                       .passiveFilterEnable = kPORT_PassiveFilterDisable,
                                       /* Open drain output is disabled */
                                       .openDrainEnable = kPORT_OpenDrainDisable,
                                       /* Low drive strength is configured */
                                       .driveStrength = kPORT_LowDriveStrength,
                                       /* Normal drive strength is configured */
                                       .driveStrength1 = kPORT_NormalDriveStrength,
                                       /* Pin is configured as P3_18 */
                                       .mux = kPORT_MuxAlt0,
                                       /* Digital input enabled */
                                       .inputBuffer = kPORT_InputBufferEnable,
                                       /* Digital input is not inverted */
                                       .invertInput = kPORT_InputNormal,
                                       /* Pin Control Register fields [15:0] are not locked */
                                       .lockRegister = kPORT_UnlockRegister};
    /* PORT3_18 (pin 86) is configured as P3_18 */
    PORT_SetPinConfig(BOARD_INITLEDSPINS_LED_RED_PORT, BOARD_INITLEDSPINS_LED_RED_PIN, &LED_RED);

    const port_pin_config_t LED_GREEN = {/* Internal pull-up/down resistor is disabled */
                                         .pullSelect = kPORT_PullDisable,
                                         /* Low internal pull resistor value is selected. */
                                         .pullValueSelect = kPORT_LowPullResistor,
                                         /* Fast slew rate is configured */
                                         .slewRate = kPORT_FastSlewRate,
                                         /* Passive input filter is disabled */
                                         .passiveFilterEnable = kPORT_PassiveFilterDisable,
                                         /* Open drain output is disabled */
                                         .openDrainEnable = kPORT_OpenDrainDisable,
                                         /* Low drive strength is configured */
                                         .driveStrength = kPORT_LowDriveStrength,
                                         /* Normal drive strength is configured */
                                         .driveStrength1 = kPORT_NormalDriveStrength,
                                         /* Pin is configured as P3_19 */
                                         .mux = kPORT_MuxAlt0,
                                         /* Digital input enabled */
                                         .inputBuffer = kPORT_InputBufferEnable,
                                         /* Digital input is not inverted */
                                         .invertInput = kPORT_InputNormal,
                                         /* Pin Control Register fields [15:0] are not locked */
                                         .lockRegister = kPORT_UnlockRegister};
    /* PORT3_19 (pin 85) is configured as P3_19 */
    PORT_SetPinConfig(BOARD_INITLEDSPINS_LED_GREEN_PORT, BOARD_INITLEDSPINS_LED_GREEN_PIN, &LED_GREEN);

    const port_pin_config_t LED_BLUE = {/* Internal pull-up/down resistor is disabled */
                                        .pullSelect = kPORT_PullDisable,
                                        /* Low internal pull resistor value is selected. */
                                        .pullValueSelect = kPORT_LowPullResistor,
                                        /* Fast slew rate is configured */
                                        .slewRate = kPORT_FastSlewRate,
                                        /* Passive input filter is disabled */
                                        .passiveFilterEnable = kPORT_PassiveFilterDisable,
                                        /* Open drain output is disabled */
                                        .openDrainEnable = kPORT_OpenDrainDisable,
                                        /* Low drive strength is configured */
                                        .driveStrength = kPORT_LowDriveStrength,
                                        /* Normal drive strength is configured */
                                        .driveStrength1 = kPORT_NormalDriveStrength,
                                        /* Pin is configured as P3_21 */
                                        .mux = kPORT_MuxAlt0,
                                        /* Digital input enabled */
                                        .inputBuffer = kPORT_InputBufferEnable,
                                        /* Digital input is not inverted */
                                        .invertInput = kPORT_InputNormal,
                                        /* Pin Control Register fields [15:0] are not locked */
                                        .lockRegister = kPORT_UnlockRegister};
    /* PORT3_21 (pin 82) is configured as P3_21 */
    PORT_SetPinConfig(BOARD_INITLEDSPINS_LED_BLUE_PORT, BOARD_INITLEDSPINS_LED_BLUE_PIN, &LED_BLUE);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitBUTTONsPins:
- options: {callFromInitBoot: 'false', coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '144', peripheral: GPIO1, signal: 'GPIO, 7', pin_signal: P1_7/WUU0_IN9/TRIG_OUT2/LPUART2_CTS_B/CT_INP7/CT4_MAT1/EZH_PIO3/ADC0_A23, direction: INPUT,
    slew_rate: fast, open_drain: disable, drive_strength: low, pull_select: down, pull_enable: disable, input_buffer: enable, invert_input: normal}
  - {pin_num: '115', peripheral: GPIO0, signal: 'GPIO, 6', pin_signal: P0_6/ISPMODE_N/LPI2C0_HREQ/LPSPI0_PCS1/CT_INP2/EZH_PIO2/CMP1_OUT/CLKOUT/ADC0_A15, direction: INPUT,
    slew_rate: fast, open_drain: disable, drive_strength: low, pull_select: down, pull_enable: disable, input_buffer: enable, invert_input: normal}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

